// Local Host
###
GET http://localhost:8080/players
###
GET http://localhost:8080/players/63c7509569d50b2d4a3eb034


###
GET http://localhost:8080/players/63c7509569d50b2d4a3eb035


###
GET http://localhost:8080/players/63c7509569d50b2d4a3eb036
###

POST http://localhost:8080/players HTTP/1.1
content-type: application/json

{
    "firstName": "Ken",
      "lastName": "Griffey Jr",
      "email": "thekid@mariners.com",
      "fact": "Nick name is The Kid",
      "team": "Seattle Mariners",
      "yearsPlayed": "22",
      "position": "outfielder"
}
###
PUT http://localhost:8080/players/63c7509569d50b2d4a3eb034 HTTP/1.1
content-type: application/json

{
      "firstName": "Babe",
      "lastName": "Ruth",
      "email": "thegreatbambino@nyy.com",
      "fact": "Nick name is the great bambino",
      "team": "New York Yankees",
      "yearsPlayed": "22",
      "position": "pitcher, outfielder"
}
###
DELETE http://localhost:8080/players/63c7509569d50b2d4a3eb036 HTTP/1.1


// Production
###
GET https://cse341-lessons-5-8.onrender.com/players

###
GET https://cse341-lessons-5-8.onrender.com/players/63c7509569d50b2d4a3eb034


###
GET https://cse341-lessons-5-8.onrender.com/63c7509569d50b2d4a3eb035


###
GET https://cse341-lessons-5-8.onrender.com/players/63c7509569d50b2d4a3eb036

###
POST https://cse341-lessons-5-8.onrender.com/players HTTP/1.1
content-type: application/json

{
    "firstName": "Aaron",
      "lastName": "Judge",
      "email": "thejudge@nyy.com",
      "fact": "Nick name is The Judge",
      "team": "New York Yankees"
}
###
PUT https://cse341-lessons-5-8.onrender.com/players/63c7509569d50b2d4a3eb034 HTTP/1.1
content-type: application/json

{
    "firstName": "Babe",
      "lastName": "Ruth",
      "email": "thegreatbambino@nyy.com",
      "fact": "Nick name is the great bambino",
      "team": "New York Yankees"
}
###
DELETE https://cse341-lessons-5-8.onrender.com/players/63c7509569d50b2d4a3eb036 HTTP/1.1
